root  /path/to/wikimirror/static;
location = /robots.txt {
    index  robots.txt;
}
location = /wikimirror.css {
    index  wikimirror.css;
}
location = /wikimirror.js {
    add_header  Cache-Control no-cache always;
    include     /path/to/wikimirror/conf/wiki-header.conf;
    index       wikimirror.js;
}